#!/bin/bash

disps=$(/usr/bin/xrandr)

if [[ $disps =~ "DP1-1-8 connected" ]]; then
  # /usr/bin/xrandr --output HDMI-1-3 --mode 3440x1440 --primary
  /usr/bin/xrandr --output eDP1 --mode 1920x1080 --primary
  /usr/bin/xrandr --output DP1-8 --mode 3440x1440 --right-of eDP1
  /usr/bin/xrandr --output DP1-1-8 --mode 2560x1080 --right-of DP1-8
else
  /usr/bin/xrandr --output eDP1 --mode 1920x1080 --primary
fi
