#!/bin/bash

disps=$(/usr/bin/xrandr)
if [[ ${disps} =~ "HDMI-0 connected" ]]; then
  /usr/bin/xrandr --output eDP-1-1 --mode 2560x1440 --left-of HDMI-0
  # /usr/bin/xrandr --output eDP-1-1 --off
  # /usr/bin/xrandr --output HDMI-0 --mode 3440x1440 --right-of eDP-1-1
  /usr/bin/xrandr --output HDMI-0 --mode 3440x1440 --primary
  # /usr/bin/xrandr --output HDMI-0 --mode 2560x1080 --primary
elif [[ $disps =~ "DP-0 connected" ]]; then
  # /usr/bin/xrandr --output HDMI-1-3 --mode 3440x1440 --primary
  /usr/bin/xrandr --output DP-0 --mode 3440x1440 --primary
  # /usr/bin/xrandr --output eDP-1-1 --mode 1920x1080 --right-of DP-0
  /usr/bin/xrandr --output eDP-1-1 --off
else
  /usr/bin/xrandr --output eDP-1-1 --mode 1920x1080 --primary
fi
