#!/bin/bash

disps=$(/usr/bin/xrandr)

if [[ ${disps} =~ 'DP3 connected' ]]; then
  /usr/bin/xrandr --output DP3 --mode 3440x1440 --primary
  /usr/bin/xrandr --output eDP1 --mode 1920x1200 --left-of DP3
else
  /usr/bin/xrandr --output eDP1 --mode 1920x1200 --rotate normal
fi
