#!/bin/bash

sudo apt-get update
sudo apt-get -qy dist-upgrade
sudo apt-get install -qy vim-gnome build-essential git-core xgalaga gparted
sudo apt-get install -qy vlc sysstat iotop iftop ifstat htop nmap xclip xsel
sudo apt-get install -qy libreadline-dev libssl-dev zlib1g-dev libxml2-dev
sudo apt-get install -qy libxslt-dev python-software-properties nodejs npm
sudo apt-get install -qy libmysqlclient-dev tmux gnome-tweak-tool w3m mongodb
sudo apt-get install -qy osspd gitg sudo aptitude dconf-editor curl libqt4-dev
sudo apt-get install -qy libyaml-dev python-setuptools python-yaml parallel
sudo apt-get install -qy texlive-full nfs-common eog-plugins handbrake
sudo apt-get install -qy inkscape ssh pandoc powerline wakeonlan zathura
sudo sed -i /etc/sudoers -e "s/\sALL$/ NOPASSWD:ALL/"
sudo apt-get install -qy libappindicator1
sudo apt-get install -qy compizconfig-settings-manager
sudo apt-get install -qy zsh docker.io
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['']"
# sudo add-apt-repository -y ppa:indicator-multiload/stable-daily 
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp-edge
udo add-apt-repository ppa:webupd8team/terminix
sudo apt-get update
# sudo apt-get -qy install indicator-multiload 
sudo apt -qy install gimp gimp-gmic tilix
update-alternatives --set x-terminal-emulator /usr/bin/tilix 
if [ ! -d ~/.oh-my-zsh ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

#install neovim
if [ ! -d ~/.config/nvim ]; then
  sudo add-apt-repository -y ppa:neovim-ppa/unstable
  sudo apt-get update
  sudo apt-get -qy install neovim python-dev python-pip python3-dev python3-pip

  sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
  sudo update-alternatives --config vi
  sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
  sudo update-alternatives --config editor
  if [ ! -d ~/.config ]; then
    mkdir ~/.config
  fi
  cd ~/.config
  ln -s ~/.vim nvim
  ln -s ~/.vimrc nvim/init.vim
  sudo pip2 install neovim
  sudo pip3 install setuptools
  sudo pip3 install neovim
fi

sudo apt-get -qy install linux-image-extra-$(uname -r)
sudo apt-get -qy install apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
pip install docker-compose

if [ ! -d ~/src ]; then
  mkdir ~/src
fi

if [ ! -d ~/src/dotfiles ]; then
  git clone https://github.com/dimus/dotfiles.git src/dotfiles
else
  cd ~/src/dotfiles
  git pull
fi

cd
if [ ! -L .vimrc ]; then
  ln -s ~/src/dotfiles/.vim .
  ln -s ~/src/dotfiles/.vimrc .
  ln -s ~/src/dotfiles/.gitconfig .
  ln -s ~/src/dotfiles/.git_colors .
  ln -s ~/src/dotfiles/.bash_aliases .
  ln -s ~/src/dotfiles/.gemrc .
  ln -s ~/src/dotfiles/unix/.gvimrc .
  ln -s ~/src/dotfiles/.tmux.conf .
  ln -s ~/src/dotfiles/.ideavimrc .
  ln -s ~/src/dotfiles/.xinitrc .
  ln -s ~/src/dotfiles/.inputrc .
  ln -s ~/Downloads dl
  mkdir code
  mkdir scala
  mkdir docker
  mkdir kubernetes
fi

if ! hash docker-compose 2>/dev/null; then
  sudo easy_install pip
  sudo -H pip install docker-compose
fi

gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier "<Super>"

if [ ! -d ~/.rbenv ]; then
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  git clone https://github.com/rkh/rbenv-update.git ~/.rbenv/plugins/rbenv-update
fi

if ! grep -Fq "rbenv" ~/.bashrc; then
  echo "no rbenv in .bashrc, adding"
  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
  echo 'eval "$(rbenv init -)"' >> ~/.bashrc
  source ~/.bashrc
fi

