#!/bin/bash
sudo apt-get update
sudo apt-get dist-upgrade -qy
sudo apt-get install -qy vim-gnome build-essential git-core xgalaga gparted
sudo apt-get install -qy vlc sysstat iotop iftop ifstat htop nmap xclip xsel
sudo apt-get install -qy libreadline-dev libssl-dev zlib1g-dev libxml2-dev
sudo apt-get install -qy libxslt-dev python-software-properties nodejs npm
sudo apt-get install -qy libmysqlclient-dev tmux gnome-tweak-tool w3m httpie
sudo apt-get install -qy osspd gitg sudo aptitude dconf-editor curl libqt4-dev
sudo apt-get install -qy libyaml-dev python-setuptools python-yaml parallel
sudo apt-get install -qy texlive-full 
sudo apt-get install -qy nfs-common eog-plugins pandoc wakeonlan \
  ruby-dev zlib1g-dev liblzma-dev inkscape powerline autoconf fonts-firacode \
  openjdk-8-jdk icedtea-netx zathura network-manager-openconnect-gnome \
  postgresql-client-common postgresql-client zsh openvpn network-manager-openvpn-gnome
sudo apt-get install -qy i3 i3status dmenu i3lock xbacklight feg conky scrot
sudo sed -i /etc/sudoers -e "s/\sALL$/ NOPASSWD:ALL/"
sudo apt-get install -y libappindicator1 exuberant-ctags
sudo apt-get install -y compizconfig-settings-manager
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['']"
# sudo add-apt-repository -y ppa:indicator-multiload/stable-daily
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp-edge
sudo add-apt-repository -y ppa:webupd8team/terminix
sudo apt-get update
sudo apt-get -qy install gimp gimp-gmic tilix
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install git-lfs

#install neovim
if [ ! -d ~/.config/nvim ]; then
  sudo add-apt-repository -y ppa:neovim-ppa/unstable
  sudo apt-get update
  sudo apt-get -qy install neovim python-dev python-pip python3-dev python3-pip

  sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
  sudo update-alternatives --config vi
  sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
  sudo update-alternatives --config editor

  if [ ! -d ~/.config ]; then
    mkdir ~/.config
  fi

  cd ~/.config
  ln -s ~/.vim nvim
  ln -s ~/.vimrc nvim/init.vim
  sudo pip2 install neovim
  sudo pip3 install setuptools
  sudo pip3 install neovim
fi

sudo apt-get -qy install linux-image-extra-$(uname -r)
sudo apt-get -qy install apt-transport-https ca-certificates
sudo rm /etc/apt/sources.list.d/docker.list*
sudo apt-get -qy install docker.io
sudo pip install docker-compose

if [ ! -d ~/src ]; then
  mkdir ~/src
fi

if [ ! -d ~/src/dotfiles ]; then
  git clone https://github.com/dimus/dotfiles.git src/dotfiles
else
  cd ~/src/dotfiles
  git pull
fi

sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp ~/src/dotfiles/unix/etc/X11/xorg.conf.d/51-synaptic-quirks.conf /etc/X11/xorg.conf.d


cd
if [ ! -L .vimrc ]; then
  ln -s ~/src/dotfiles/.vim .
  ln -s ~/src/dotfiles/.vimrc .
  ln -s ~/src/dotfiles/.gitconfig .
  ln -s ~/src/dotfiles/.git_colors .
  ln -s ~/src/dotfiles/.bash_aliases .
  ln -s ~/src/dotfiles/.gemrc .
  ln -s ~/src/dotfiles/unix/.gvimrc .
  ln -s ~/src/dotfiles/.tmux.conf .
  ln -s ~/src/dotfiles/.ideavimrc .
  ln -s ~/src/dotfiles/.xinitrc .
  ln -s ~/Downloads dl
  mkdir code
  mkdir scala
  mkdir docker
fi

if ! hash docker-compose 2>/dev/null; then
  sudo easy_install pip
  sudo -H pip install docker-compose
fi

gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier "<Super>"

if [ ! -d ~/.rbenv ]; then
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  git clone https://github.com/rkh/rbenv-update.git ~/.rbenv/plugins/rbenv-update
fi

if ! grep -Fq "rbenv" ~/.bashrc; then
  echo "no rbenv in .bashrc, adding"
  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
  echo 'eval "$(rbenv init -)"' >> ~/.bashrc
  source ~/.bashrc
fi


sudo update-alternatives --config x-terminal-emulator
